### ISSUE TITLE
System.InvalidCastException

### ISSUE THREAD

**Issue by neokeats** [DEVSENSE/Parsers#3]
`
System.InvalidCastException: Unable to cast object of type &apos;Devsense.PHP.Syntax.Ast.UnaryEx&apos; to type &apos;Devsense.PHP.Syntax.Ast.VarLikeConstructUse&apos;.&#x000D;&#x000A;   at Devsense.PHP.Syntax.Ast.BasicNodesFactory.Call(Span span, TranslatedQualifiedName name, CallSignature signature, LangElement memberOfOpt)&#x000D;&#x000A;   at Devsense.PHP.Syntax.Parser.DoAction(Int32 action)&#x000D;&#x000A;   at Devsense.PHP.Syntax.ShiftReduceParser`2.Reduce(Int32 rule_nr)&#x000D;&#x000A;   at Devsense.PHP.Syntax.ShiftReduceParser`2.Parse()&#x000D;&#x000A;   at Devsense.PHP.Syntax.Parser.Parse(ITokenProvider`2 lexer, INodesFactory`2 astFactory, LanguageFeatures language, IErrorSink`1 errors, Int32 positionShift)&#x000D;&#x000A;   at &#x001C;&#x001B;&#x0007;&#x0005;&#x000A;&#x0018;&#x0012;&#x001A;&#x000E;&#x001A;&#x0004;&#x0018;&#x0010;&#x0009;&#x0011;&#x000F;&#x001B;&#x0003;&#x000E;&#x0006;&#x0014;&#x000F;&#x001A;&#x000F;&#x001A;.Parse(INodesFactory`2 factory, IErrorSink`1 errors)
`

**Comment by michalbrabec** [comment]
The conversion exception has been fixed.
The solution is tested by automatic unit tests.
The solution is available via NuGet update.

**Comment by jakubmisek** [comment]
fixed in https://github.com/DEVSENSE/Parsers/commit/7db268fc3dda7890993bd15cbd1ddf8b96dfdf34

**Comment by neokeats** [comment]
hi, 
thanx

**Comment by jakubmisek** [comment]
Thank you too!
